name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        run: |
          curl -s "https://api.render.com/deploy/srv-d78119ua2pns73b3ld6g?key=qA4MaNmRuNo"
